// This file was generated by [deno-specta](https://github.com/whymidnight/deno-specta). Do not edit this file manually.

((globalThis) => {
  const { core } = Deno;
  const { ops } = core;
  core.initializeAsyncOps();

  function argsToMessage(...args) {
    return args.map((arg) => JSON.stringify(arg)).join(" ");
  }

  globalThis.console = {
    log: (...args) => {
      core.print(`[out]: ${argsToMessage(...args)}\n`, false);
    },
    error: (...args) => {
      core.print(`[err]: ${argsToMessage(...args)}\n`, true);
    },
  };

  globalThis.runjs = {
    /* 
    * @param myName: string
    * @returns Promise<string>
    */
    helloWorld:  (myName) => {
      return  ops.hello_world(myName)
    },
    /* 
    * @param myName: string
    * @param yourName: string
    * @returns Promise<string>
    */
    secondHelloWorld: async (myName, yourName) => {
      return await ops.second_hello_world(myName, yourName)
    },
  };
})(globalThis);
